### ISSUE TITLE
The generated Cityscapes dataset

### ISSUE THREAD

**Issue by seabearlmx** [yurujaja/DGInStyle-SegModel#1]
Hello! This is a nice work. Could you plan to release the generated Cityscapes dataset?

**Comment by yurujaja** [comment]
This is not currently in our plans.

**Comment by amundra15** [comment]
Hi @seabearlmx 

My current understanding is that the authors fine-tuned the diffusion model only on the GTA dataset and used that to generate a synthetic GTA dataset. I didn't see any mention of a synthetic Cityscapes dataset. Could you please elaborate on which dataset you were referring to?
